services:
  node1:
    container_name: node1
    build:
      context: ./nodes/node1
      dockerfile: Dockerfile.host
      args:
        ARG_NODE_LABEL: node1
    restart: always
  node2:
    container_name: node2
    build:
      context: ./nodes/node2
      dockerfile: Dockerfile.host
      args:
        ARG_NODE_LABEL: node2
    restart: always

  control:
    container_name: control
    image: alpine/ansible:latest
    command: tail -f /dev/null
    volumes:
      - ./nodes/controller/data:/ansible
      - ./nodes/controller/ssh:/root/.ssh
    working_dir: /ansible
    tty: true
    stdin_open: true
